export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const CART_ERROR = "CART_ERROR";
export const SEND_CART_NOTIFICATIONS_SUCCESS =
  "SEND_CART_NOTIFICATIONS_SUCCESS";
export const SEND_CART_NOTIFICATIONS_FAIL = "SEND_CART_NOTIFICATIONS_FAIL";
export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITEMS_SUCCESS";
export const GET_CART_ITEMS_FAIL = "GET_CART_ITEMS_FAIL";
