export const CREATE_EXCHANGE_REQUEST = 'CREATE_EXCHANGE_REQUEST';
export const CREATE_EXCHANGE_SUCCESS = 'CREATE_EXCHANGE_SUCCESS';
export const CREATE_EXCHANGE_FAIL = 'CREATE_EXCHANGE_FAIL';
export const CREATE_EXCHANGE_RESET = 'CREATE_EXCHANGE_RESET';

export const MY_EXCHANGES_REQUEST = 'MY_EXCHANGES_REQUEST';
export const MY_EXCHANGES_SUCCESS = 'MY_EXCHANGES_SUCCESS';
export const MY_EXCHANGES_FAIL = 'MY_EXCHANGES_FAIL';

export const ALL_EXCHANGES_REQUEST = 'ALL_EXCHANGES_REQUEST';
export const ALL_EXCHANGES_SUCCESS = 'ALL_EXCHANGES_SUCCESS';
export const ALL_EXCHANGES_FAIL = 'ALL_EXCHANGES_FAIL';

export const UPDATE_EXCHANGE_REQUEST = 'UPDATE_EXCHANGE_REQUEST';
export const UPDATE_EXCHANGE_SUCCESS = 'UPDATE_EXCHANGE_SUCCESS';
export const UPDATE_EXCHANGE_FAIL = 'UPDATE_EXCHANGE_FAIL';
export const UPDATE_EXCHANGE_RESET = 'UPDATE_EXCHANGE_RESET';

export const DELETE_EXCHANGE_REQUEST = 'DELETE_EXCHANGE_REQUEST';
export const DELETE_EXCHANGE_SUCCESS = 'DELETE_EXCHANGE_SUCCESS';
export const DELETE_EXCHANGE_FAIL = 'DELETE_EXCHANGE_FAIL';
export const DELETE_EXCHANGE_RESET = 'DELETE_EXCHANGE_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS'; 